# Generated by Django 5.2.7 on 2025-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("other_name", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("lga", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employees",
                "ordering": ["-created_at"],
            },
        ),
    ]
